version: '3.1'

services: 
  picfit:
    image: impishindustries/picfit
    ports:
      - 3001:3001      
    env_file:
      - ./env/local-storage.env
    volumes: 
      - ./config:/config
      - ./image-storage:/image-storage
      